-- =============================================
-- ONE-TIME CLEANUP: Drop Redundant Indexes
-- =============================================
-- This script removes old, manually-created indexes.
-- It is designed to clean up legacy indexes that are now managed by Prisma.
-- Note: The index names used here might follow an old naming convention
-- (e.g., "TableName_columnName_idx") and may differ from the names
-- automatically generated by Prisma.
-- It is safe to run this script multiple times.

-- USERS
DROP INDEX IF EXISTS "User_email_idx";
DROP INDEX IF EXISTS "User_stripeCustomerId_idx";
DROP INDEX IF EXISTS "User_type_role_idx";
DROP INDEX IF EXISTS "User_createdAt_desc_idx";
DROP INDEX IF EXISTS "User_id_role_idx";
DROP INDEX IF EXISTS "User_id_type_subscription_idx";
DROP INDEX IF EXISTS "User_type_subscription_active_idx";
DROP INDEX IF EXISTS "User_role_admin_idx";

-- CATEGORIES
DROP INDEX IF EXISTS "Category_slug_idx";
DROP INDEX IF EXISTS "Category_parentId_name_idx";
DROP INDEX IF EXISTS "Category_name_idx";

-- TAGS
DROP INDEX IF EXISTS "Tag_slug_idx";
DROP INDEX IF EXISTS "Tag_name_idx";

-- POSTS
DROP INDEX IF EXISTS "Post_slug_idx";
DROP INDEX IF EXISTS "Post_isPublished_status_idx";
DROP INDEX IF EXISTS "Post_authorId_isPublished_status_idx";
DROP INDEX IF EXISTS "Post_isPremium_isPublished_status_idx";
DROP INDEX IF EXISTS "Post_authorId_status_idx";
DROP INDEX IF EXISTS "Post_isPublished_createdAt_desc_isPremium_idx";
DROP INDEX IF EXISTS "Post_createdAt_desc_published_approved_idx";
DROP INDEX IF EXISTS "Post_premium_published_approved_idx";
DROP INDEX IF EXISTS "Post_authorId_createdAt_desc_idx";
DROP INDEX IF EXISTS "Post_authorId_status_createdAt_idx";
DROP INDEX IF EXISTS "Post_isFeatured_isPublished_idx";
DROP INDEX IF EXISTS "Post_isFeatured_createdAt_desc_idx";
DROP INDEX IF EXISTS "Post_featured_published_approved_idx";
DROP INDEX IF EXISTS "Post_featured_premium_published_idx";

-- BOOKMARKS
DROP INDEX IF EXISTS "Bookmark_userId_postId_idx";
DROP INDEX IF EXISTS "Bookmark_userId_createdAt_desc_idx";

-- FAVORITES
DROP INDEX IF EXISTS "Favorite_userId_postId_idx";
DROP INDEX IF EXISTS "Favorite_userId_createdAt_desc_idx";
DROP INDEX IF EXISTS "Favorite_postId_createdAt_desc_idx";
DROP INDEX IF EXISTS "Favorite_postId_count_idx";

-- VIEWS
DROP INDEX IF EXISTS "View_postId_idx";
DROP INDEX IF EXISTS "View_createdAt_desc_postId_idx";
DROP INDEX IF EXISTS "View_postId_ipAddress_unique_idx";

-- LOGS
DROP INDEX IF EXISTS "Log_createdAt_desc_idx";
DROP INDEX IF EXISTS "Log_userId_createdAt_desc_idx";
DROP INDEX IF EXISTS "Log_action_createdAt_desc_idx";
DROP INDEX IF EXISTS "Log_severity_createdAt_desc_idx";
DROP INDEX IF EXISTS "Log_entityType_entityId_idx";
DROP INDEX IF EXISTS "Log_severity_action_createdAt_idx";
DROP INDEX IF EXISTS "Log_userId_action_createdAt_idx";

-- SETTINGS
DROP INDEX IF EXISTS "Settings_storageType_idx";
DROP INDEX IF EXISTS "Settings_updatedBy_idx";
DROP INDEX IF EXISTS "Settings_createdAt_desc_idx";
DROP INDEX IF EXISTS "Settings_updatedAt_desc_idx";

-- MEDIA
-- No legacy indexes to remove for this table as it is new.

SELECT 'Index cleanup script executed successfully! 🧹' as result;