import { PrismaClient } from "../lib/generated/prisma";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Starting database seed...");

  // Create parent categories
  const geminiCategory = await prisma.category.upsert({
    where: { slug: "gemini" },
    update: {},
    create: {
      name: "Gemini",
      slug: "gemini",
      description: "Google's Gemini AI prompts and tools",
    },
  });

  const aiCodeEditorCategory = await prisma.category.upsert({
    where: { slug: "ai-code-editor" },
    update: {},
    create: {
      name: "Ai Code Editor",
      slug: "ai-code-editor",
      description: "AI-powered code editor tools and prompts",
    },
  });

  await prisma.category.upsert({
    where: { slug: "claude" },
    update: {},
    create: {
      name: "Claude",
      slug: "claude",
      description: "Anthropic Claude prompts and tools",
    },
  });

  await prisma.category.upsert({
    where: { slug: "text-to-audio" },
    update: {},
    create: {
      name: "Text to Audio",
      slug: "text-to-audio",
      description: "AI audio generation prompts",
    },
  });

  await prisma.category.upsert({
    where: { slug: "chatgpt" },
    update: {},
    create: {
      name: "ChatGPT",
      slug: "chatgpt",
      description: "OpenAI ChatGPT prompts and examples",
    },
  });

  await prisma.category.upsert({
    where: { slug: "text-to-image" },
    update: {},
    create: {
      name: "Text-to-Image",
      slug: "text-to-image",
      description: "AI image generation prompts",
    },
  });

  await prisma.category.upsert({
    where: { slug: "text-to-video" },
    update: {},
    create: {
      name: "Text-to-Video",
      slug: "text-to-video",
      description: "AI video generation prompts",
    },
  });

  console.log("✅ Created parent categories");

  // Create child categories
  await prisma.category.upsert({
    where: { slug: "veo3" },
    update: {},
    create: {
      name: "Veo3",
      slug: "veo3",
      description: "Google's Veo3 video generation tool",
      parentId: geminiCategory.id,
    },
  });

  await prisma.category.upsert({
    where: { slug: "image-generator" },
    update: {},
    create: {
      name: "Image Generator",
      slug: "image-generator",
      description: "Gemini's image generation capabilities",
      parentId: geminiCategory.id,
    },
  });

  await prisma.category.upsert({
    where: { slug: "whisk" },
    update: {},
    create: {
      name: "Whisk",
      slug: "whisk",
      description: "Google's Whisk creative tool",
      parentId: geminiCategory.id,
    },
  });

  await prisma.category.upsert({
    where: { slug: "cursor-rules" },
    update: {},
    create: {
      name: "Cursor Rules",
      slug: "cursor-rules",
      description: "Cursor code editor rules and automations",
      parentId: aiCodeEditorCategory.id,
    },
  });

  await prisma.category.upsert({
    where: { slug: "windsurf-rules" },
    update: {},
    create: {
      name: "Windsurf Rules",
      slug: "windsurf-rules",
      description: "Windsurf code editor rules and automations",
      parentId: aiCodeEditorCategory.id,
    },
  });

  await prisma.category.upsert({
    where: { slug: "chatgpt-rules" },
    update: {},
    create: {
      name: "ChatGPT Rules",
      slug: "chatgpt-rules",
      description: "ChatGPT code editor rules and automations",
      parentId: aiCodeEditorCategory.id,
    },
  });

  console.log("✅ Created child categories");

  // Create tags
  const tags = [
    { name: "owl", slug: "owl" },
    { name: "moonlit", slug: "moonlit" },
    { name: "cinematic", slug: "cinematic" },
    { name: "nature", slug: "nature" },
    { name: "forest", slug: "forest" },
    { name: "creative", slug: "creative" },
    { name: "artistic", slug: "artistic" },
    { name: "professional", slug: "professional" },
    { name: "cyberpunk", slug: "cyberpunk" },
    { name: "futuristic", slug: "futuristic" },
    { name: "neon", slug: "neon" },
    { name: "cityscape", slug: "cityscape" },
    { name: "landscape", slug: "landscape" },
    { name: "peaceful", slug: "peaceful" },
    { name: "mountains", slug: "mountains" },
    { name: "dragon", slug: "dragon" },
    { name: "fantasy", slug: "fantasy" },
    { name: "medieval", slug: "medieval" },
    { name: "castle", slug: "castle" },
    { name: "epic", slug: "epic" },
    { name: "underwater", slug: "underwater" },
    { name: "coral", slug: "coral" },
    { name: "marine", slug: "marine" },
    { name: "tropical", slug: "tropical" },
    { name: "ocean", slug: "ocean" },
    { name: "steampunk", slug: "steampunk" },
    { name: "victorian", slug: "victorian" },
    { name: "workshop", slug: "workshop" },
    { name: "brass", slug: "brass" },
    { name: "inventor", slug: "inventor" },
    { name: "space", slug: "space" },
    { name: "earth", slug: "earth" },
    { name: "sunrise", slug: "sunrise" },
    { name: "orbital", slug: "orbital" },
    { name: "cosmic", slug: "cosmic" },
    { name: "autumn", slug: "autumn" },
    { name: "cabin", slug: "cabin" },
    { name: "cozy", slug: "cozy" },
    { name: "hyper realistic", slug: "hyper-realistic" },
    { name: "photorealistic", slug: "photorealistic" },
    { name: "8K", slug: "8k" },
    { name: "4K", slug: "4k" },
    { name: "high-resolution", slug: "high-resolution" },
    { name: "detailed", slug: "detailed" },
    { name: "intricate", slug: "intricate" },
    { name: "insanely detailed", slug: "insanely-detailed" },
    { name: "cinematic lighting", slug: "cinematic-lighting" },
    { name: "sharp focus", slug: "sharp-focus" },
    { name: "studio quality", slug: "studio-quality" },
    { name: "beautiful", slug: "beautiful" },
    { name: "smooth", slug: "smooth" },
    { name: "colorful background", slug: "colorful-background" },
    { name: "dramatic", slug: "dramatic" },
    { name: "photograph", slug: "photograph" },
    { name: "art", slug: "art" },
    { name: "digital painting", slug: "digital-painting" },
    { name: "oil painting", slug: "oil-painting" },
    { name: "watercolor", slug: "watercolor" },
    { name: "illustration", slug: "illustration" },
    { name: "anime", slug: "anime" },
    { name: "surreal", slug: "surreal" },
    { name: "abstract", slug: "abstract" },
    { name: "impressionist", slug: "impressionist" },
    { name: "cubist", slug: "cubist" },
    { name: "pop art", slug: "pop-art" },
    { name: "fantasy art", slug: "fantasy-art" },
    { name: "sci-fi", slug: "sci-fi" },
    { name: "by Van Gogh", slug: "by-van-gogh" },
    { name: "portrait", slug: "portrait" },
    { name: "nature", slug: "nature" },
    { name: "animals", slug: "animals" },
    { name: "fantasy creatures", slug: "fantasy-creatures" },
    { name: "futuristic", slug: "futuristic" },
    { name: "historical", slug: "historical" },
    { name: "celestial", slug: "celestial" },
    { name: "serene", slug: "serene" },
    { name: "mysterious", slug: "mysterious" },
    { name: "whimsical", slug: "whimsical" },
    { name: "ethereal", slug: "ethereal" },
    { name: "nostalgic", slug: "nostalgic" },
    { name: "close-up", slug: "close-up" },
    { name: "wide shot", slug: "wide-shot" },
    { name: "full body shot", slug: "full-body-shot" },
    { name: "dramatic lighting", slug: "dramatic-lighting" },
    { name: "soft light", slug: "soft-light" },
    { name: "golden hour", slug: "golden-hour" },
    { name: "backlit", slug: "backlit" },
    { name: "depth of field", slug: "depth-of-field" },
    { name: "rule of thirds", slug: "rule-of-thirds" },
    { name: "symmetrical", slug: "symmetrical" },
    { name: "vibrant colors", slug: "vibrant-colors" },
    { name: "monochromatic", slug: "monochromatic" },
    { name: "pastel", slug: "pastel" },
    { name: "earth tones", slug: "earth-tones" },
    { name: "rough", slug: "rough" },
    { name: "grainy", slug: "grainy" },
    { name: "metallic", slug: "metallic" },
    { name: "glossy", slug: "glossy" },
    { name: "moving", slug: "moving" },
    { name: "soaring", slug: "soaring" },
    { name: "walking", slug: "walking" },
    { name: "running", slug: "running" },
    { name: "flying", slug: "flying" },
    { name: "zooming", slug: "zooming" },
    { name: "panning", slug: "panning" },
    { name: "tilting", slug: "tilting" },
    { name: "orbiting", slug: "orbiting" },
    { name: "tracking shot", slug: "tracking-shot" },
    { name: "medium shot", slug: "medium-shot" },
    { name: "low-angle shot", slug: "low-angle-shot" },
    { name: "high-angle shot", slug: "high-angle-shot" },
    { name: "aerial view", slug: "aerial-view" },
    { name: "dolly in/out", slug: "dolly-in-out" },
    { name: "pan left/right", slug: "pan-left-right" },
    { name: "tilt up/down", slug: "tilt-up-down" },
    { name: "cinematic", slug: "cinematic" },
    { name: "shot on film", slug: "shot-on-film" },
    { name: "slow motion", slug: "slow-motion" },
    { name: "fast motion", slug: "fast-motion" },
    { name: "short loop", slug: "short-loop" },
    { name: "seamless loop", slug: "seamless-loop" },
    { name: "realistic", slug: "realistic" },
    { name: "cartoon", slug: "cartoon" },
    { name: "animated", slug: "animated" },
    { name: "ultrarealistic", slug: "ultrarealistic" },
    { name: "super-realistic", slug: "super-realistic" },
    { name: "hyper-detailed", slug: "hyper-detailed" },
    { name: "crystal clear", slug: "crystal-clear" },
    { name: "sharp", slug: "sharp" },
    { name: "crisp", slug: "crisp" },
    { name: "fine detail", slug: "fine-detail" },
    { name: "masterwork", slug: "masterwork" },
    { name: "masterpiece", slug: "masterpiece" },
    { name: "award-winning", slug: "award-winning" },
    { name: "professional photo", slug: "professional-photo" },
    { name: "DSLR photo", slug: "dslr-photo" },
    { name: "high fidelity", slug: "high-fidelity" },
    { name: "authentic", slug: "authentic" },
    { name: "lifelike", slug: "lifelike" },
    { name: "true to life", slug: "true-to-life" },
    { name: "natural light", slug: "natural-light" },
    { name: "diffused light", slug: "diffused-light" },
    { name: "volumetric lighting", slug: "volumetric-lighting" },
    { name: "ray tracing", slug: "ray-tracing" },
    { name: "global illumination", slug: "global-illumination" },
    { name: "ambient occlusion", slug: "ambient-occlusion" },
    { name: "Unreal Engine", slug: "unreal-engine" },
    { name: "Octane Render", slug: "octane-render" },
    { name: "Cycles Render", slug: "cycles-render" },
    { name: "V-Ray", slug: "v-ray" },
    { name: "Corona Renderer", slug: "corona-renderer" },
    { name: "Blender", slug: "blender" },
    { name: "ZBrush", slug: "zbrush" },
    { name: "Substance Painter", slug: "substance-painter" },
    { name: "Marvelous Designer", slug: "marvelous-designer" },
    { name: "pencil sketch", slug: "pencil-sketch" },
    { name: "charcoal drawing", slug: "charcoal-drawing" },
    { name: "pastel drawing", slug: "pastel-drawing" },
    { name: "ink drawing", slug: "ink-drawing" },
    { name: "pen and ink", slug: "pen-and-ink" },
    { name: "line art", slug: "line-art" },
    { name: "dot art", slug: "dot-art" },
    { name: "stipple", slug: "stipple" },
    { name: "cross-hatching", slug: "cross-hatching" },
    { name: "woodcut", slug: "woodcut" },
    { name: "linocut", slug: "linocut" },
    { name: "etching", slug: "etching" },
    { name: "engraving", slug: "engraving" },
    { name: "lithography", slug: "lithography" },
    { name: "fresco", slug: "fresco" },
    { name: "mosaic", slug: "mosaic" },
    { name: "stained glass", slug: "stained-glass" },
    { name: "sculpture", slug: "sculpture" },
    { name: "pottery", slug: "pottery" },
    { name: "ceramic", slug: "ceramic" },
    { name: "textile art", slug: "textile-art" },
    { name: "embroidery", slug: "embroidery" },
    { name: "crochet", slug: "crochet" },
    { name: "knitting", slug: "knitting" },
    { name: "papercraft", slug: "papercraft" },
    { name: "origami", slug: "origami" },
    { name: "collage", slug: "collage" },
    { name: "mixed media", slug: "mixed-media" },
    { name: "street art", slug: "street-art" },
    { name: "graffiti", slug: "graffiti" },
    { name: "mural", slug: "mural" },
    { name: "chalk art", slug: "chalk-art" },
    { name: "sand art", slug: "sand-art" },
    { name: "body paint", slug: "body-paint" },
    { name: "tattoo", slug: "tattoo" },
    { name: "pixel art", slug: "pixel-art" },
    { name: "voxel art", slug: "voxel-art" },
    { name: "vector art", slug: "vector-art" },
    { name: "flat design", slug: "flat-design" },
    { name: "minimalist", slug: "minimalist" },
    { name: "maximalist", slug: "maximalist" },
    { name: "gothic", slug: "gothic" },
    { name: "baroque", slug: "baroque" },
    { name: "rococo", slug: "rococo" },
    { name: "neoclassical", slug: "neoclassical" },
    { name: "romanticism", slug: "romanticism" },
    { name: "pre-raphaelite", slug: "pre-raphaelite" },
    { name: "art nouveau", slug: "art-nouveau" },
    { name: "art deco", slug: "art-deco" },
    { name: "fauvism", slug: "fauvism" },
    { name: "expressionism", slug: "expressionism" },
    { name: "futurism", slug: "futurism" },
    { name: "dadaism", slug: "dadaism" },
    { name: "constructivism", slug: "constructivism" },
    { name: "de Stijl", slug: "de-stijl" },
    { name: "Bauhaus", slug: "bauhaus" },
    { name: "suprematism", slug: "suprematism" },
    { name: "conceptual art", slug: "conceptual-art" },
    { name: "installation art", slug: "installation-art" },
    { name: "performance art", slug: "performance-art" },
    { name: "environmental art", slug: "environmental-art" },
    { name: "land art", slug: "land-art" },
    { name: "generative art", slug: "generative-art" },
    { name: "algorithmic art", slug: "algorithmic-art" },
    { name: "glitch art", slug: "glitch-art" },
    { name: "risograph", slug: "risograph" },
    { name: "cel-shaded", slug: "cel-shaded" },
    { name: "comic book", slug: "comic-book" },
    { name: "graphic novel", slug: "graphic-novel" },
    { name: "manga", slug: "manga" },
    { name: "Disney style", slug: "disney-style" },
    { name: "Pixar style", slug: "pixar-style" },
    { name: "Ghibli style", slug: "ghibli-style" },
    { name: "Looney Tunes style", slug: "looney-tunes-style" },
    { name: "old school animation", slug: "old-school-animation" },
    { name: "stop motion", slug: "stop-motion" },
    { name: "claymation", slug: "claymation" },
    { name: "rotoscoping", slug: "rotoscoping" },
    { name: "person", slug: "person" },
    { name: "man", slug: "man" },
    { name: "woman", slug: "woman" },
    { name: "child", slug: "child" },
    { name: "girl", slug: "girl" },
    { name: "boy", slug: "boy" },
    { name: "baby", slug: "baby" },
    { name: "elderly", slug: "elderly" },
    { name: "diverse", slug: "diverse" },
    { name: "character design", slug: "character-design" },
    { name: "hero", slug: "hero" },
    { name: "villain", slug: "villain" },
    { name: "warrior", slug: "warrior" },
    { name: "knight", slug: "knight" },
    { name: "wizard", slug: "wizard" },
    { name: "witch", slug: "witch" },
    { name: "elf", slug: "elf" },
    { name: "dwarf", slug: "dwarf" },
    { name: "goblin", slug: "goblin" },
    { name: "alien", slug: "alien" },
    { name: "robot", slug: "robot" },
    { name: "cyborg", slug: "cyborg" },
    { name: "android", slug: "android" },
    { name: "mecha", slug: "mecha" },
    { name: "superhero", slug: "superhero" },
    { name: "princess", slug: "princess" },
    { name: "queen", slug: "queen" },
    { name: "king", slug: "king" },
    { name: "emperor", slug: "emperor" },
    { name: "empress", slug: "empress" },
    { name: "god", slug: "god" },
    { name: "goddess", slug: "goddess" },
    { name: "mythological creature", slug: "mythological-creature" },
    { name: "unicorn", slug: "unicorn" },
    { name: "griffin", slug: "griffin" },
    { name: "phoenix", slug: "phoenix" },
    { name: "mermaid", slug: "mermaid" },
    { name: "centaur", slug: "centaur" },
    { name: "sphinx", slug: "sphinx" },
    { name: "monster", slug: "monster" },
    { name: "demon", slug: "demon" },
    { name: "angel", slug: "angel" },
    { name: "spirit", slug: "spirit" },
    { name: "ghost", slug: "ghost" },
    { name: "zombie", slug: "zombie" },
    { name: "vampire", slug: "vampire" },
    { name: "werewolf", slug: "werewolf" },
    { name: "animal", slug: "animal" },
    { name: "dog", slug: "dog" },
    { name: "cat", slug: "cat" },
    { name: "bird", slug: "bird" },
    { name: "fish", slug: "fish" },
    { name: "reptile", slug: "reptile" },
    { name: "amphibian", slug: "amphibian" },
    { name: "insect", slug: "insect" },
    { name: "mammal", slug: "mammal" },
    { name: "flora", slug: "flora" },
    { name: "fauna", slug: "fauna" },
    { name: "tree", slug: "tree" },
    { name: "flower", slug: "flower" },
    { name: "plant", slug: "plant" },
    { name: "jungle", slug: "jungle" },
    { name: "desert", slug: "desert" },
    { name: "mountain", slug: "mountain" },
    { name: "volcano", slug: "volcano" },
    { name: "river", slug: "river" },
    { name: "lake", slug: "lake" },
    { name: "beach", slug: "beach" },
    { name: "island", slug: "island" },
    { name: "cave", slug: "cave" },
    { name: "waterfall", slug: "waterfall" },
    { name: "city", slug: "city" },
    { name: "town", slug: "town" },
    { name: "village", slug: "village" },
    { name: "ruins", slug: "ruins" },
    { name: "temple", slug: "temple" },
    { name: "church", slug: "church" },
    { name: "house", slug: "house" },
    { name: "apartment", slug: "apartment" },
    { name: "skyscraper", slug: "skyscraper" },
    { name: "bridge", slug: "bridge" },
    { name: "vehicle", slug: "vehicle" },
    { name: "car", slug: "car" },
    { name: "train", slug: "train" },
    { name: "plane", slug: "plane" },
    { name: "ship", slug: "ship" },
    { name: "spaceship", slug: "spaceship" },
    { name: "bike", slug: "bike" },
    { name: "motorcycle", slug: "motorcycle" },
    { name: "futuristic vehicle", slug: "futuristic-vehicle" },
    { name: "vintage car", slug: "vintage-car" },
    { name: "antique", slug: "antique" },
    { name: "modern", slug: "modern" },
    { name: "abstract shape", slug: "abstract-shape" },
    { name: "geometric form", slug: "geometric-form" },
    { name: "swirl", slug: "swirl" },
    { name: "fractal", slug: "fractal" },
    { name: "pattern", slug: "pattern" },
    { name: "texture", slug: "texture" },
    { name: "food", slug: "food" },
    { name: "drink", slug: "drink" },
    { name: "fruit", slug: "fruit" },
    { name: "vegetable", slug: "vegetable" },
    { name: "dessert", slug: "dessert" },
    { name: "meal", slug: "meal" },
    { name: "object", slug: "object" },
    { name: "instrument", slug: "instrument" },
    { name: "tool", slug: "tool" },
    { name: "weapon", slug: "weapon" },
    { name: "armor", slug: "armor" },
    { name: "clothing", slug: "clothing" },
    { name: "jewelry", slug: "jewelry" },
    { name: "furniture", slug: "furniture" },
    { name: "gadget", slug: "gadget" },
    { name: "technology", slug: "technology" },
    { name: "machine", slug: "machine" },
    { name: "abstract concept", slug: "abstract-concept" },
    { name: "idea", slug: "idea" },
    { name: "emotion", slug: "emotion" },
    { name: "dream", slug: "dream" },
    { name: "nightmare", slug: "nightmare" },
    { name: "memory", slug: "memory" },
    { name: "full shot", slug: "full-shot" },
    { name: "long shot", slug: "long-shot" },
    { name: "extreme close-up", slug: "extreme-close-up" },
    { name: "extreme wide shot", slug: "extreme-wide-shot" },
    { name: "dutch angle", slug: "dutch-angle" },
    { name: "bird's eye view", slug: "birds-eye-view" },
    { name: "worm's eye view", slug: "worms-eye-view" },
    { name: "eye-level", slug: "eye-level" },
    { name: "low angle", slug: "low-angle" },
    { name: "high angle", slug: "high-angle" },
    { name: "point of view (POV)", slug: "point-of-view-pov" },
    { name: "over-the-shoulder", slug: "over-the-shoulder" },
    { name: "symmetrical composition", slug: "symmetrical-composition" },
    { name: "asymmetrical", slug: "asymmetrical" },
    { name: "leading lines", slug: "leading-lines" },
    { name: "negative space", slug: "negative-space" },
    { name: "foreground", slug: "foreground" },
    { name: "midground", slug: "midground" },
    { name: "background", slug: "background" },
    { name: "panoramic", slug: "panoramic" },
    { name: "diorama", slug: "diorama" },
    { name: "miniature", slug: "miniature" },
    { name: "macro", slug: "macro" },
    { name: "micro", slug: "micro" },
    { name: "tilt-shift", slug: "tilt-shift" },
    { name: "bokeh", slug: "bokeh" },
    { name: "shallow depth of field", slug: "shallow-depth-of-field" },
    { name: "deep depth of field", slug: "deep-depth-of-field" },
    { name: "wide aperture", slug: "wide-aperture" },
    { name: "narrow aperture", slug: "narrow-aperture" },
    { name: "long exposure", slug: "long-exposure" },
    { name: "short exposure", slug: "short-exposure" },
    { name: "freeze frame", slug: "freeze-frame" },
    { name: "motion blur", slug: "motion-blur" },
    { name: "soft focus", slug: "soft-focus" },
    { name: "out of focus", slug: "out-of-focus" },
    { name: "vibrant", slug: "vibrant" },
    { name: "vivid", slug: "vivid" },
    { name: "rich", slug: "rich" },
    { name: "deep", slug: "deep" },
    { name: "saturated", slug: "saturated" },
    { name: "muted", slug: "muted" },
    { name: "desaturated", slug: "desaturated" },
    { name: "monochrome", slug: "monochrome" },
    { name: "grayscale", slug: "grayscale" },
    { name: "sepia", slug: "sepia" },
    { name: "warm tones", slug: "warm-tones" },
    { name: "cool tones", slug: "cool-tones" },
    { name: "jewel tones", slug: "jewel-tones" },
    { name: "iridescent", slug: "iridescent" },
    { name: "pearlescent", slug: "pearlescent" },
    { name: "glowing", slug: "glowing" },
    { name: "luminous", slug: "luminous" },
    { name: "shimmering", slug: "shimmering" },
    { name: "sparkling", slug: "sparkling" },
    { name: "subtle colors", slug: "subtle-colors" },
    { name: "analogous colors", slug: "analogous-colors" },
    { name: "complementary colors", slug: "complementary-colors" },
    { name: "harmonious colors", slug: "harmonious-colors" },
    { name: "chaotic colors", slug: "chaotic-colors" },
    { name: "happy", slug: "happy" },
    { name: "joyful", slug: "joyful" },
    { name: "sad", slug: "sad" },
    { name: "melancholic", slug: "melancholic" },
    { name: "angry", slug: "angry" },
    { name: "intense", slug: "intense" },
    { name: "calm", slug: "calm" },
    { name: "peaceful", slug: "peaceful" },
    { name: "serene", slug: "serene" },
    { name: "tranquil", slug: "tranquil" },
    { name: "dreamlike", slug: "dreamlike" },
    { name: "nightmarish", slug: "nightmarish" },
    { name: "mystical", slug: "mystical" },
    { name: "magical", slug: "magical" },
    { name: "epic", slug: "epic" },
    { name: "grand", slug: "grand" },
    { name: "powerful", slug: "powerful" },
    { name: "delicate", slug: "delicate" },
    { name: "fragile", slug: "fragile" },
    { name: "innocent", slug: "innocent" },
    { name: "playful", slug: "playful" },
    { name: "ominous", slug: "ominous" },
    { name: "eerie", slug: "eerie" },
    { name: "haunting", slug: "haunting" },
    { name: "spooky", slug: "spooky" },
    { name: "bizarre", slug: "bizarre" },
    { name: "dystopian", slug: "dystopian" },
    { name: "utopian", slug: "utopian" },
    { name: "fantastical", slug: "fantastical" },
    { name: "ancient", slug: "ancient" },
    { name: "retro", slug: "retro" },
    { name: "vintage", slug: "vintage" },
    { name: "smooth motion", slug: "smooth-motion" },
    { name: "fluid animation", slug: "fluid-animation" },
    { name: "dynamic movement", slug: "dynamic-movement" },
    { name: "subtle motion", slug: "subtle-motion" },
    { name: "camera pan", slug: "camera-pan" },
    { name: "camera tilt", slug: "camera-tilt" },
    { name: "camera zoom", slug: "camera-zoom" },
    { name: "dolly shot", slug: "dolly-shot" },
    { name: "crane shot", slug: "crane-shot" },
    { name: "steadycam", slug: "steadycam" },
    { name: "handheld", slug: "handheld" },
    { name: "tracking shot", slug: "tracking-shot" },
    { name: "POV shot", slug: "pov-shot" },
    { name: "slow-motion", slug: "slow-motion" },
    { name: "fast-motion", slug: "fast-motion" },
    { name: "time-lapse", slug: "time-lapse" },
    { name: "hyperlapse", slug: "hyperlapse" },
    { name: "bullet time", slug: "bullet-time" },
    { name: "cinematic shot", slug: "cinematic-shot" },
    { name: "establishing shot", slug: "establishing-shot" },
    { name: "reaction shot", slug: "reaction-shot" },
    { name: "cutaway", slug: "cutaway" },
    { name: "montage", slug: "montage" },
    { name: "dissolve", slug: "dissolve" },
    { name: "fade in/out", slug: "fade-in-out" },
    { name: "wipe", slug: "wipe" },
    { name: "cross-fade", slug: "cross-fade" },
    { name: "smash cut", slug: "smash-cut" },
    { name: "jump cut", slug: "jump-cut" },
    { name: "match cut", slug: "match-cut" },
    { name: "seamless transition", slug: "seamless-transition" },
    { name: "glitch effect", slug: "glitch-effect" },
    { name: "distortion", slug: "distortion" },
    { name: "pixelation", slug: "pixelation" },
    { name: "chromatic aberration", slug: "chromatic-aberration" },
    { name: "lens flare", slug: "lens-flare" },
    { name: "film grain", slug: "film-grain" },
    { name: "noise", slug: "noise" },
    { name: "VHS effect", slug: "vhs-effect" },
    { name: "retro video", slug: "retro-video" },
    { name: "surveillance footage", slug: "surveillance-footage" },
    { name: "security camera", slug: "security-camera" },
    { name: "drone footage", slug: "drone-footage" },
    { name: "aerial video", slug: "aerial-video" },
    { name: "underwater video", slug: "underwater-video" },
    { name: "POV video", slug: "pov-video" },
    { name: "animated loop", slug: "animated-loop" },
    { name: "looping video", slug: "looping-video" },
    { name: "short video", slug: "short-video" },
    { name: "GIF", slug: "gif" },
    { name: "visual effects (VFX)", slug: "visual-effects-vfx" },
    { name: "special effects (SFX)", slug: "special-effects-sfx" },
    { name: "CGI", slug: "cgi" },
    { name: "greenscreen", slug: "greenscreen" },
    { name: "bluescreen", slug: "bluescreen" },
    { name: "motion tracking", slug: "motion-tracking" },
    { name: "particle effects", slug: "particle-effects" },
    { name: "smoke", slug: "smoke" },
    { name: "fire", slug: "fire" },
    { name: "water", slug: "water" },
    { name: "explosion", slug: "explosion" },
    { name: "dust", slug: "dust" },
    { name: "magic", slug: "magic" },
    { name: "energy", slug: "energy" },
    { name: "force field", slug: "force-field" },
    { name: "holographic", slug: "holographic" },
    { name: "projection", slug: "projection" },
    { name: "screen", slug: "screen" },
    { name: "display", slug: "display" },
    { name: "UI", slug: "ui" },
    { name: "HUD", slug: "hud" },
    { name: "data visualization", slug: "data-visualization" },
    { name: "abstract animation", slug: "abstract-animation" },
    { name: "kinetic typography", slug: "kinetic-typography" },
    { name: "studio lighting", slug: "studio-lighting" },
    { name: "artificial light", slug: "artificial-light" },
    { name: "overhead light", slug: "overhead-light" },
    { name: "side light", slug: "side-light" },
    { name: "back light", slug: "back-light" },
    { name: "rim light", slug: "rim-light" },
    { name: "silhouette", slug: "silhouette" },
    { name: "volumetric light", slug: "volumetric-light" },
    { name: "god rays", slug: "god-rays" },
    { name: "sun rays", slug: "sun-rays" },
    { name: "moonlight", slug: "moonlight" },
    { name: "starlight", slug: "starlight" },
    { name: "city lights", slug: "city-lights" },
    { name: "neon lights", slug: "neon-lights" },
    { name: "ambient light", slug: "ambient-light" },
    { name: "harsh light", slug: "harsh-light" },
    { name: "warm light", slug: "warm-light" },
    { name: "cool light", slug: "cool-light" },
    { name: "chiaroscuro", slug: "chiaroscuro" },
    { name: "tenebrism", slug: "tenebrism" },
    { name: "high contrast", slug: "high-contrast" },
    { name: "low contrast", slug: "low-contrast" },
    { name: "fog", slug: "fog" },
    { name: "mist", slug: "mist" },
    { name: "haze", slug: "haze" },
    { name: "rain", slug: "rain" },
    { name: "snow", slug: "snow" },
    { name: "thunder", slug: "thunder" },
    { name: "lightning", slug: "lightning" },
    { name: "stormy", slug: "stormy" },
    { name: "clear", slug: "clear" },
    { name: "sunny", slug: "sunny" },
    { name: "cloudy", slug: "cloudy" },
    { name: "overcast", slug: "overcast" },
    { name: "dawn", slug: "dawn" },
    { name: "dusk", slug: "dusk" },
    { name: "sunrise", slug: "sunrise" },
    { name: "sunset", slug: "sunset" },
    { name: "blue hour", slug: "blue-hour" },
    { name: "night", slug: "night" },
    { name: "day", slug: "day" },
  ];

  for (const tag of tags) {
    await prisma.tag.upsert({
      where: { slug: tag.slug },
      update: {},
      create: tag,
    });
  }

  console.log("✅ Created tags");
  console.log("🎉 Database seeded successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
